# Generated by Django 4.0.2 on 2022-02-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavhasi')),
                ('price', models.CharField(max_length=100, verbose_name='narxi')),
                ('sub_description', models.TextField(max_length=300, verbose_name='Qisqa malumot')),
                ('description1', models.TextField(max_length=1000, verbose_name='Malumot 1')),
                ('description2', models.TextField(blank=True, max_length=1000, verbose_name='Malumot 2')),
                ('description3', models.TextField(blank=True, max_length=1000, verbose_name='Malumot 3')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Rasmi')),
            ],
            options={
                'verbose_name': 'Kurslar',
                'verbose_name_plural': 'Kurslar',
            },
        ),
    ]
