# Generated by Django 4.0.2 on 2022-02-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='slug',
            field=models.SlugField(default='ingliz tili ', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
