# Generated by Django 4.0.2 on 2022-02-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_featuredcourse_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredcourse',
            name='title',
        ),
    ]
