# Generated by Django 4.0.2 on 2022-02-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_featuredcourse_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.CharField(default='uzbek', max_length=200, verbose_name='Davomiyligi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='instructor',
            field=models.CharField(default='1 oy', max_length=200, verbose_name='O`qituvchi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='language',
            field=models.CharField(default='uzbek', max_length=200, verbose_name='Kurs tili'),
            preserve_default=False,
        ),
    ]
