# Generated by Django 4.0.2 on 2022-02-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=300)),
                ('title', models.TextField(max_length=500)),
                ('button1', models.CharField(max_length=100)),
                ('slug_button1', models.CharField(max_length=100)),
                ('button2', models.CharField(max_length=100)),
                ('slug_button2', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='headerlogo',
            options={'verbose_name': 'Header Logo', 'verbose_name_plural': 'Header Logo'},
        ),
    ]
