# Generated by Django 4.0.2 on 2022-02-16 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hometitle_alter_headerlogo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hometitle',
            options={'verbose_name': 'Home Title', 'verbose_name_plural': 'Home Title'},
        ),
    ]
