# Generated by Django 4.0.2 on 2022-02-16 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Blog', to='home.blog')),
            ],
            options={
                'verbose_name': 'Home Blog',
                'verbose_name_plural': 'Home Blog',
            },
        ),
    ]
