# Generated by Django 4.0.2 on 2022-02-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_course_homeblog_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeblog',
            name='title',
        ),
    ]
