# Generated by Django 4.0.2 on 2022-02-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_homeblog_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Logo')),
                ('description', models.TextField(max_length=400, verbose_name='Malumot')),
            ],
            options={
                'verbose_name': 'Footer Meta',
                'verbose_name_plural': 'Footer Meta',
            },
        ),
    ]
