# Generated by Django 4.0.2 on 2022-02-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_footermeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footermeta',
            name='image',
        ),
        migrations.AddField(
            model_name='footermeta',
            name='title',
            field=models.CharField(default='Biz haqimizda', max_length=200),
            preserve_default=False,
        ),
    ]
