# Generated by Django 4.0.2 on 2022-02-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_aloqa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aloqa',
            name='email',
        ),
    ]
