# Generated by Django 4.0.2 on 2022-02-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_aloqa_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='footermeta',
            name='facebook',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='footermeta',
            name='instagram',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='footermeta',
            name='telegram',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='footermeta',
            name='youtube',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
