# Generated by Django 4.0.2 on 2022-02-17 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_footermeta_facebook_footermeta_instagram_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterMeta',
        ),
    ]
