# Generated by Django 4.0.2 on 2022-02-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_delete_footermeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeblog',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='HomeBlog',
        ),
    ]
