# Generated by Django 4.0.2 on 2022-02-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_homeblog_blog_delete_blog_delete_homeblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerlogo',
            name='status',
            field=models.CharField(default='true', max_length=200, verbose_name=(('True', 'Mavjud'), ('False', 'Mavjud Emas'))),
            preserve_default=False,
        ),
    ]
