# Generated by Django 4.0.2 on 2022-02-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_headerlogo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerlogo',
            name='status',
            field=models.CharField(choices=[('True', 'Mavjud'), ('False', 'Mavjud Emas')], max_length=200),
        ),
    ]
