# Generated by Django 4.0.2 on 2022-02-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_headerlogo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerlogo',
            name='status',
            field=models.CharField(choices=[('published', 'Mavjud'), ('draft', 'Mavjud Emas')], max_length=200),
        ),
    ]
