# Generated by Django 4.0.2 on 2022-02-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_headerlogo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerlogo',
            name='status',
            field=models.CharField(choices=[(0, 'draft'), (1, 'published')], max_length=200),
        ),
    ]
