# Generated by Django 4.0.2 on 2022-02-17 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_headerlogo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headerlogo',
            name='status',
        ),
    ]
