# Generated by Django 4.0.2 on 2022-02-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_headerlogo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AloqaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=500)),
                ('create_time', models.TimeField(auto_now=True, null=True)),
                ('create_date', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Aloqa Formasi',
                'verbose_name_plural': 'Aloqa Formasi',
            },
        ),
        migrations.DeleteModel(
            name='Aloqa',
        ),
    ]
