# Generated by Django 4.0.2 on 2022-02-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(max_length=400, verbose_name='Malumot')),
                ('instagram', models.CharField(blank=True, max_length=200)),
                ('telegram', models.CharField(blank=True, max_length=200)),
                ('youtube', models.CharField(blank=True, max_length=200)),
                ('facebook', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Footer Meta',
                'verbose_name_plural': 'Footer Meta',
            },
        ),
    ]
