# Generated by Django 4.0.2 on 2022-02-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContactMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=400)),
            ],
            options={
                'verbose_name': 'Footer Aloqa Malumoti',
                'verbose_name_plural': 'Footer Aloqa Malumoti',
            },
        ),
        migrations.AlterModelOptions(
            name='footermeta',
            options={'verbose_name': 'Footer Biz haqimizda', 'verbose_name_plural': 'Footer Biz haqimizda'},
        ),
    ]
